name: flutterchi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

#environment:
#  sdk: ^3.9.0
#
environment:
  sdk: ^3.2.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  step_progress_indicator: ^1.0.2
  widgetbook: ^3.17.0
  widgetbook_annotation: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.17.0
  build_runner: ^2.8.0

flutter:
  uses-material-design: true
